# Travis-CI Build for rugged
# see travis-ci.org for details

language: ruby

# Ruby versions to test against
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - rbx-20mode

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: rbx-20mode

install:
  - bundle install --deployment
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake libssh2-1-dev openssh-client openssh-server

script: script/cibuild

# Notify development list when needed
notifications:
  recipients:
    - vicent@github.com
  email:
    on_success: change
    on_failure: always
